/* * * * * * *
 * Guess.java
 * @author Ben Durham
 * @version 20170923
 * A game to make the user guess a random number generated by the computer.
 */

import java.util.Scanner;
import java.util.Random;

public class Guess {

	final static int MAX = 100; 	// Declares a maximum random number
	
	public static void main(String[] args) {
		
		// Creates new instances of Scanner and Random
		Scanner in = new Scanner(System.in);
		Random gen = new Random();

		// Generates a random number
		int num = gen.nextInt(MAX);
	
		// Prompts the user for input	
		System.out.printf("I'm thinking of a number between 0 and %d (inclusive).\n", MAX);
		System.out.printf("Can you guess what it is?\n", MAX);
		System.out.print("Type your guess: ");
		int guess = in.nextInt();
	
		// Reveals the random number
		System.out.printf("The number I was thinking of was %d.\n", num);

		// Reacts accordingly
		if (guess > num) {
			System.out.printf("You were %d over.\n", guess - num);
		} else if (num > guess) {
			System.out.printf("You were %d under.\n", num - guess);
		} else {
			System.out.println("You guessed it! Congratulations");
		}
		
	}
}
