/* * * * * * *
 * Guess.java
 * @author Ben Durham
 * @version 20170923
 * A game to make the user guess a random number generated by the computer.
 */

import java.util.Scanner;
import java.util.Random;

public class Guess {

	final static int MAX = 100; 	// Declares a maximum random number
	
	public static void main(String[] args) {
		
		// Creates new instances of Scanner and Random
		Scanner in = new Scanner(System.in);
		Random gen = new Random();

		// Generates a random number
		int num = gen.nextInt(MAX);
	
		// Prompts the user for input	
		System.out.printf("I'm thinking of a number between 0 and %d (inclusive).\n", MAX);
		System.out.printf("Can you guess what it is?\n", MAX);

		int incorrect_tries = 0;
		
		while (incorrect_tries < 3) {
			
			System.out.print("Type your guess: ");
			int guess = in.nextInt();

			// Reacts accordingly
			if (guess > num) {
				System.out.println("You guessed too high. Try again!");
				incorrect_tries++;
			} else if (num > guess) {
				System.out.println("You guess too low. Try again!");
				incorrect_tries++;
			} else {
				System.out.println("You guessed it! Congratulations");
				break;
			}
		}
		
		// Reveals the random number
		System.out.printf("The number I was thinking of was %d.\n", num);
		System.out.println("Better luck next time!");
		
	}
}
